name: aes_encryption
description: Provided end to end AES Encryption to be converted on JavaScript backend.
version: 1.0.1
homepage: https://github.com/Flutter-Postal-Service/aes-encryption

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  encrypt: ^5.0.1
  tuple: ^2.0.0
  crypto: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter