name: aes_encryption
description: A new Flutter package project.
version: 1.0.0
homepage: https://github.com/Flutter-Postal-Service/aes-encryption

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  encrypt: ^5.0.1
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter